"""
Enhanced Configuration Manager v3.0
Centralized config with workspace, search, and agent settings.
"""
import os
import re
import sys
import logging
from pathlib import Path
from dotenv import load_dotenv

logger = logging.getLogger("JARVIS.CONFIG")


def get_project_root() -> Path:
    """Detect project root directory."""
    current = Path(__file__).resolve()
    if current.parent.name == "backend":
        return current.parent.parent
    return current.parent


PROJECT_ROOT = get_project_root()
env_path = PROJECT_ROOT / ".env"
if env_path.exists():
    load_dotenv(dotenv_path=str(env_path))
else:
    load_dotenv()


class Config:
    """Centralized configuration with agent-level settings."""

    # ─── Paths ───
    PROJECT_ROOT: Path = PROJECT_ROOT
    BACKEND_DIR: Path = PROJECT_ROOT / "backend"
    DATA_DIR: Path = BACKEND_DIR / "data"

    # ─── API Keys ───
    GROQ_API_KEY: str = os.getenv("GROQ_API_KEY", "")

    # ─── LLM ───
    LLM_MODEL: str = os.getenv("LLM_MODEL", "llama-3.3-70b-versatile")
    WHISPER_MODEL: str = os.getenv("WHISPER_MODEL", "whisper-large-v3")

    # ─── TTS ───
    TTS_VOICE: str = os.getenv("TTS_VOICE", "en-US-GuyNeural")
    TTS_RATE: str = os.getenv("TTS_RATE", "+0%")
    TTS_PITCH: str = os.getenv("TTS_PITCH", "+0Hz")

    # ─── Server ───
    HOST: str = os.getenv("HOST", "0.0.0.0")
    PORT: int = int(os.getenv("PORT", "8000"))
    DEBUG: bool = os.getenv("DEBUG", "false").lower() == "true"

    # ─── Memory ───
    MEMORY_FILE: str = os.getenv("MEMORY_FILE", str(DATA_DIR / "memory.json"))
    MEMORY_MAX_MESSAGES: int = int(os.getenv("MEMORY_MAX_MESSAGES", "20"))
    MEMORY_SUMMARIZE_THRESHOLD: int = int(os.getenv("MEMORY_SUMMARIZE_THRESHOLD", "20"))

    # ─── Skills ───
    SKILLS_ENABLED: bool = os.getenv("SKILLS_ENABLED", "true").lower() == "true"

    # ─── WORKSPACE & CODE SETTINGS (NEW v3.0) ───
    WORKSPACE_DIR: Path = Path(os.getenv("WORKSPACE_DIR", str(Path.home() / "projects")))
    SEARCH_DIRS: list = [
        Path(p.strip())
        for p in os.getenv("SEARCH_DIRS", str(WORKSPACE_DIR)).split(",")
        if p.strip()
    ]
    CODE_SAVE_DIR: Path = Path(os.getenv("CODE_SAVE_DIR", str(WORKSPACE_DIR / "jarvis-generated")))
    MAX_FILE_SIZE_KB: int = int(os.getenv("MAX_FILE_SIZE_KB", "5000"))

    # ─── AGENT SETTINGS (NEW v3.0) ───
    AGENT_MAX_STEPS: int = int(os.getenv("AGENT_MAX_STEPS", "10"))
    AGENT_AUTO_CORRECT: bool = os.getenv("AGENT_AUTO_CORRECT", "true").lower() == "true"
    AGENT_LEARN_PREFERENCES: bool = os.getenv("AGENT_LEARN_PREFERENCES", "true").lower() == "true"
    AGENT_CODE_TIMEOUT: int = int(os.getenv("AGENT_CODE_TIMEOUT", "30"))

    # ─── Supported Languages for Code Gen ───
    CODE_LANGUAGES: dict = {
        "python": ".py",
        "javascript": ".js",
        "typescript": ".ts",
        "java": ".java",
        "cpp": ".cpp",
        "c": ".c",
        "go": ".go",
        "rust": ".rs",
        "ruby": ".rb",
        "php": ".php",
        "swift": ".swift",
        "kotlin": ".kt",
        "html": ".html",
        "css": ".css",
        "sql": ".sql",
        "bash": ".sh",
        "powershell": ".ps1",
    }

    # ─── Project Templates ───
    PROJECT_TEMPLATES: dict = {
        "react": {
            "dirs": ["src/components", "src/hooks", "src/styles", "public"],
            "files": {
                "package.json": '{"name": "{{name}}", "version": "0.1.0", "dependencies": {"react": "^18", "react-dom": "^18", "react-scripts": "5.0.1"}, "scripts": {"start": "react-scripts start", "build": "react-scripts build"}}',
                "public/index.html": '<!DOCTYPE html><html><head><title>{{name}}</title></head><body><div id="root"></div></body></html>',
                "src/index.js": 'import React from "react"; import ReactDOM from "react-dom/client"; import App from "./App"; import "./styles/index.css"; const root = ReactDOM.createRoot(document.getElementById("root")); root.render(<App />);',
                "src/App.js": 'import React from "react"; import "./styles/App.css"; function App() { return <div className="App"><h1>Welcome to {{name}}</h1></div>; } export default App;',
                "src/styles/App.css": ".App { text-align: center; padding: 20px; }",
                "src/styles/index.css": "* { margin: 0; padding: 0; box-sizing: border-box; }",
            },
        },
        "python": {
            "dirs": ["src", "tests", "docs"],
            "files": {
                "requirements.txt": "",
                "src/__init__.py": "",
                "src/main.py": "def main():\n    print('Hello from {{name}}!')\n\nif __name__ == '__main__':\n    main()",
                "README.md": "# {{name}}\n\nPython project generated by JARVIS.",
            },
        },
        "node": {
            "dirs": ["src", "tests", "config"],
            "files": {
                "package.json": '{"name": "{{name}}", "version": "1.0.0", "main": "src/index.js", "scripts": {"start": "node src/index.js", "dev": "nodemon src/index.js"}}',
                "src/index.js": "console.log('Hello from {{name}}!');",
                "README.md": "# {{name}}\\n\\nNode.js project generated by JARVIS.",
            },
        },
        "fastapi": {
            "dirs": ["app", "app/api", "app/models", "app/services", "tests"],
            "files": {
                "requirements.txt": "fastapi>=0.115.0\nuvicorn[standard]>=0.30.0\npydantic>=2.9.0\npython-dotenv>=1.0.0\nhttpx>=0.27.0",
                "app/__init__.py": "",
                "app/main.py": "from fastapi import FastAPI\nfrom app.api import routes\n\napp = FastAPI(title='{{name}}', version='1.0.0')\napp.include_router(routes.router, prefix='/api')\n\n@app.get('/')\ndef root():\n    return {'message': 'Welcome to {{name}}'}",
                "app/api/__init__.py": "",
                "app/api/routes.py": "from fastapi import APIRouter\nrouter = APIRouter()\n\n@router.get('/health')\ndef health():\n    return {'status': 'ok'}",
                "app/models/__init__.py": "",
                "app/services/__init__.py": "",
                "README.md": "# {{name}}\\n\\nFastAPI project generated by JARVIS.\\n\\n## Run\\n```\\nuvicorn app.main:app --reload\\n```",
            },
        },
    }

    # ─── File Type Icons for Display ───
    FILE_ICONS: dict = {
        ".py": "🐍", ".js": "📜", ".ts": "🔷", ".jsx": "⚛️", ".tsx": "⚛️",
        ".java": "☕", ".cpp": "🔧", ".c": "🔧", ".go": "🐹", ".rs": "🦀",
        ".rb": "💎", ".php": "🐘", ".swift": "🍎", ".kt": "📱",
        ".html": "🌐", ".css": "🎨", ".scss": "🎨", ".json": "📋",
        ".md": "📝", ".txt": "📄", ".sql": "🗄️", ".sh": "🐚",
        ".yml": "⚙️", ".yaml": "⚙️", ".env": "🔐", ".gitignore": "🚫",
        "folder": "📁", "default": "📄",
    }

    # ─── App Launch Maps (Enhanced) ───
    WINDOWS_APP_MAP: dict = {
        "notepad": "notepad.exe",
        "calculator": "calc.exe",
        "paint": "mspaint.exe",
        "cmd": "cmd.exe",
        "terminal": "wt.exe",
        "powershell": "powershell.exe",
        "explorer": "explorer.exe",
        "task manager": "taskmgr.exe",
        "chrome": "start chrome",
        "firefox": "start firefox",
        "edge": "start msedge",
        "brave": "start brave",
        "opera": "start opera",
        "vscode": "code",
        "vs code": "code",
        "code": "code",
        "word": "start winword",
        "excel": "start excel",
        "powerpoint": "start powerpnt",
        "outlook": "start outlook",
        "teams": "start teams",
        "spotify": "start spotify",
        "whatsapp": "start whatsapp",
        "discord": "start discord",
        "slack": "start slack",
        "zoom": "start zoom",
        "obs": "start obs64",
        "steam": "start steam",
        "epic": "start com.epicgames.launcher",
        "vlc": "start vlc",
        "notepad++": "start notepad++",
        "postman": "start postman",
        "figma": "start figma",
        "github desktop": "start github",
        "docker desktop": "start docker desktop",
        "pycharm": "pycharm64",
        "intellij": "idea64",
        "android studio": "studio64",
        "filezilla": "filezilla",
        "putty": "putty",
        "winrar": "winrar",
        "7zip": "7zFM",
        "blender": "blender",
        "photoshop": "photoshop",
        "illustrator": "illustrator",
        "premiere": "adobe premiere pro",
        "after effects": "afterfx",
        "davinci": "resolve",
        "obsidian": "obsidian",
    }

    MAC_APP_MAP: dict = {
        "notepad": "TextEdit",
        "calculator": "Calculator",
        "chrome": "Google Chrome",
        "firefox": "Firefox",
        "brave": "Brave Browser",
        "safari": "Safari",
        "edge": "Microsoft Edge",
        "vscode": "Visual Studio Code",
        "vs code": "Visual Studio Code",
        "code": "Visual Studio Code",
        "spotify": "Spotify",
        "discord": "Discord",
        "slack": "Slack",
        "zoom": "zoom.us",
        "obs": "OBS",
        "steam": "Steam",
        "vlc": "VLC",
        "postman": "Postman",
        "figma": "Figma",
        "docker": "Docker Desktop",
        "pycharm": "PyCharm",
        "intellij": "IntelliJ IDEA",
        "android studio": "Android Studio",
        "blender": "Blender",
        "photoshop": "Adobe Photoshop",
        "illustrator": "Adobe Illustrator",
        "premiere": "Adobe Premiere Pro",
        "obsidian": "Obsidian",
        "iterm": "iTerm",
        "terminal": "Terminal",
    }

    WEB_FALLBACK_MAP: dict = {
        "whatsapp": "https://web.whatsapp.com",
        "vscode": "https://vscode.dev",
        "vs code": "https://vscode.dev",
        "code": "https://vscode.dev",
        "excel": "https://www.office.com/launch/excel",
        "word": "https://www.office.com/launch/word",
        "powerpoint": "https://www.office.com/launch/powerpoint",
        "outlook": "https://outlook.live.com",
        "teams": "https://teams.microsoft.com",
        "youtube": "https://youtube.com",
        "github": "https://github.com",
        "gitlab": "https://gitlab.com",
        "bitbucket": "https://bitbucket.org",
        "instagram": "https://instagram.com",
        "facebook": "https://facebook.com",
        "twitter": "https://twitter.com",
        "x": "https://x.com",
        "linkedin": "https://linkedin.com",
        "reddit": "https://reddit.com",
        "spotify": "https://open.spotify.com",
        "gmail": "https://mail.google.com",
        "drive": "https://drive.google.com",
        "google": "https://google.com",
        "maps": "https://maps.google.com",
        "claude": "https://claude.ai",
        "chatgpt": "https://chat.openai.com",
        "perplexity": "https://perplexity.ai",
        "notion": "https://notion.so",
        "trello": "https://trello.com",
        "asana": "https://asana.com",
        "figma": "https://figma.com",
        "canva": "https://canva.com",
        "netflix": "https://netflix.com",
        "amazon": "https://amazon.com",
        "flipkart": "https://flipkart.com",
        "discord": "https://discord.com/app",
    }


# ─── Validation ───
if not Config.GROQ_API_KEY:
    logger.warning("GROQ_API_KEY not found in environment. Set it in .env file.")

# ─── Ensure directories exist ───
Config.DATA_DIR.mkdir(parents=True, exist_ok=True)
Config.WORKSPACE_DIR.mkdir(parents=True, exist_ok=True)
Config.CODE_SAVE_DIR.mkdir(parents=True, exist_ok=True)

for d in Config.SEARCH_DIRS:
    d.mkdir(parents=True, exist_ok=True)

config = Config()
